# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import eav.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='datatype',
            field=eav.fields.EavDatatypeField(choices=[('text', 'Text'), ('date', 'Date'), ('float', 'Float'), ('int', 'Integer'), ('bool', 'True / False'), ('object', 'Django Object'), ('enum', 'Multiple Choice')], max_length=6, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='description',
            field=models.CharField(blank=True, help_text='Short description', max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='display_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='enum_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eav.EnumGroup', verbose_name='Choice Group'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(help_text='User-friendly attribute name', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=eav.fields.EavSlugField(help_text='Short unique attribute label', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='value',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='value',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
