# Generated by Django 3.0.2 on 2020-09-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('eav', '0002_add_new_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='value',
            unique_together={('entity_ct', 'entity_id', 'attribute_id')},
        ),
    ]
