# Generated by Django 4.2.6 on 2023-10-13 10:19

from django.db import migrations, models
import eav.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0009_enchance_naming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='datatype',
            field=eav.fields.EavDatatypeField(
                choices=[
                    ('text', 'Texte'),
                    ('date', 'Date'),
                    ('float', 'Nombre décimal'),
                    ('int', 'Entier'),
                    ('bool', 'Vrai / Faux'),
                    ('object', 'Django Object'),
                    ('enum', 'Multiple Choice'),
                    ('json', 'JSON Object'),
                    ('csv', 'Comma-Separated-Value'),
                ],
                max_length=6,
                verbose_name='Data Type',
            ),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='enumgroup',
            name='id',
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='enumvalue',
            name='id',
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='id',
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
