# Generated by Django 4.2.11 on 2024-03-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0009_enchance_naming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.CharField(
                editable=False, max_length=40, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='enumgroup',
            name='id',
            field=models.CharField(
                editable=False, max_length=40, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='enumvalue',
            name='id',
            field=models.CharField(
                editable=False, max_length=40, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name='value',
            name='id',
            field=models.CharField(
                editable=False, max_length=40, primary_key=True, serialize=False
            ),
        ),
    ]
